name: business_ai
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - scikit-learn
  - xgboost
  - jupyterlab
  - pip
  - pip:
      - pytimetk
      - openai
      - langchain
      - langchain_openai
      - langchain-experimental
      - streamlit
      - pypdf
      - google-api-python-client 
      - pytube
      - youtube-transcript-api
      - PyYAML
      - chromadb
      - h2o
      - langgraph==0.0.48
      - langchain_groq
     


